# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: GPU Training Course
author: Liam J Berrisford, Stephen Cook

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# _config.yml
sphinx:
  config:
    html_extra_path:
      - _static/

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

execute:
  execute_notebooks: "force"
  exclude_patterns: 
      - 'lessons/theory.ipynb'
      - 'lessons/spack.ipynb'
      - 'lessons/slurm.ipynb'
      - 'lessons/conways_game_of_life.ipynb'
      - 'lessons/profiling.ipynb'
      - 'lessons/temperature_diffusion.ipynb'