# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: GPU Training Course
author: Liam J Berrisford

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# _config.yml
sphinx:
  config:
    html_extra_path:
      - _static/

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  theme:
    name: sphinx_book_theme
    options:
      # Default is something like 60–70 characters; bump it up!
      content-width: 90%        # or "1200px" if you want a fixed width
      # table-width: 100%       # (optional) stretch tables too

execute:
  execute_notebooks: "force"