site_name: "GPU Training"
theme:
  name: "material"
  features:
    - content.code.copy  # Enable copy button on code blocks
  palette:
    primary: "indigo"
    accent: "indigo"
  code:
    highlight: "github-dark"  # Customize code syntax highlighting
markdown_extensions:
  - admonition            # Enables admonition boxes
  - pymdownx.extra
  - pymdownx.superfences
  - pymdownx.details      # Optional: Adds collapsible sections
  - pymdownx.highlight    # Optional: Enhances code highlighting
docs_dir: course
nav:
  - Home: index.md        # Adds index.md as the homepage
  - Setup: lessons/00_setup.md
  - Spack: lessons/01_spack.md
  - Tips and Tricks: tips_and_tricks.md
  - Spack Cheat Sheet: spack_cheat_sheet.md
